wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.6
    start_time: 1636828607
    t:
      1:
      - 1
      3:
      - 13
      4: 3.8.6
      5: 0.12.6
      8:
      - 3
      - 5
